### ISSUE TITLE
change semantic vocab size to 500 to fit hubert quantizer

### ISSUE THREAD

**Issue by jidanhuang** [gitmylo/bark-voice-cloning-HuBERT-quantizer#21]
hi~I wonder is it possible to change semantic vocab size from 10000 to 500 to fit hubert quantizer and train semantic transformer and then coarse transformer.

**Comment by gitmylo** [comment]
This model is specifically meant to replicate Bark's vocab size so it can clone bark. But you can technically create a model with a different vocab size by providing a different output_size to the CustomTokenizer when creating the model.

You do not need this repository if you want to train Bark on semantic tokens with a vocab size of 500. This quantizer is specifically made to copy an existing quantizer, not make a new one, because that's just a normal quantizer in that case.
