### ISSUE TITLE
semantic.npy

### ISSUE THREAD

**Issue by taalua** [gitmylo/bark-voice-cloning-HuBERT-quantizer#7]
Hi, thank you for the work.
In your code, I understand that Hubert is used to extract: 
    feat_string = '_semantic_features.npy'
how about:   
    sem_string = '_semantic.npy'
where to get the *_semantic.npy?

Thank you.

**Comment by gitmylo** [comment]
Those are the files for training a custom quantizer. they can be created with https://github.com/gitmylo/bark-data-gen

(For the record, since a lot of people seem to misunderstand, you do **not** need that code for cloning a voice itsself, only if you want to train your own model (which usually isn't needed))

**Comment by taalua** [comment]
Thank you for your reply.
I checked https://github.com/gitmylo/bark-data-gen
is the *_semantic.npy is created using create_data.py ?

**Comment by gitmylo** [comment]
correct, but they will have random names, first you run create_data, then when you have enough semantics, you run create_wavs. wait until that's done. then you can zip both folders, place them in a directory /semantic and /wav.

Then do the process and process2 steps from this repo. after that, you can train your own custom quantizer.
